### PR TITLE
Fix for 'com.google.android.gms.license' bug

### PR DESCRIPTION
**Pull request by rostyk-kanafotskyy**
Related issue : [#473](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/473)

### CODE REVIEW

**Comment by Emperorlou** [comment]
Can we get this reviewed/deployed asap?

**Comment by Emperorlou** [comment]
@eddyverbruggen thanks! When will this be available on npm so phonegap build works again?

**Comment by Emperorlou** [comment]
Nevermind, I just tried it and it works! Thanks!

**Comment by petemcwilliams** [comment]
I'm getting a build error, suspect this merge is the cause, builds ok on v5.2.1

:CordovaLib:mergeDebugAssets
:mergeDebugAssets

:transformClassesWithDexBuilderForDebug

:transformDexArchiveWithExternalLibsDexMergerForDebug
 
FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
35 actionable tasks: 35 executed
(node:60252) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: /Users/petermcwilliams/Documents/appframework/madetomoveapp/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by EddyVerbruggen** [comment]
@petemcwilliams I don't see a relevant error in this log. Can you update your Android repo's locally and try again?

**Comment by petemcwilliams** [comment]
Sorry what are you referring to as updating my Android repo locally...

**Comment by EddyVerbruggen** [comment]
Open Android Studio, and update 'Android Support Repository' and 'Android Support Library' through the Android SDK manager. The plugin now pins to version 11.8.0.

_I'm not surprised this change opens up a new can of worms._

**Comment by petemcwilliams** [comment]
Ok thanks, will give that a go

**Comment by petemcwilliams** [comment]
Seems to be an issue with a conflict with other modules using google v12.0.1...

Workaround based on https://github.com/arnesson/cordova-plugin-firebase/issues/610#issuecomment-375194757 to place the build-extras.gradle in correct place

configurations.all {
   resolutionStrategy {
        force "com.google.android.gms:play-services-auth:12.0.1"
        force "com.google.android.gms:play-services-identity:12.0.1"
    }
}

Forced version was conflicting with other plugins which were using 12, for example firebase

**Pull request merged**
