### PR TITLE
Lock Google Play services version, fix when Google API don't send refreshToken back

### PR DESCRIPTION
**Pull request by madding**

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Would be nice to have some eyeballs on this one. Anyone up for a test, and fi verify it behaves nicely with other plugins using Google SDK's (push fi).

**Comment by velickym** [comment]
@madding Why passing true into requestServerAuthCode() instead of false requires locking Google Play frameworks to a specific version ?

**Comment by madding** [comment]
When pass true into requestServerAuthCode() Google API returned serverAuthCode which can used for take RefreshToken for offline access to API. 
Oldest version of Google Play framework don't send back field accessToken it explain this:
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/398

**Comment by yemenifree** [comment]
thanks this save my day 👍 

after force request server auth code google ask permission for offline access & return refresh token when use server auth code 


```php
        try {
            $this->client->authenticate($request->input('serverAuthCode'));
        } catch (InvalidArgumentException $exception) {
            return response()->json(['message' => $exception->getMessage()]);
        }
        $token = $this->client->getAccessToken();
        /*
         * [
         *      "access_token":"XXX",
         *      "token_type":"Bearer",
         *      "expires_in":3600,
         *      "refresh_token":"XXX",
         *      "id_token":"XXXX",
         *      "created":1509033140
         * ]
         */
```

**Comment by Bramzor** [comment]
@EddyVerbruggen Can you review this one: https://github.com/EddyVerbruggen/cordova-plugin-googleplus/commit/db504777156c08d5e5db7245bda8104907ad5cd1  because it seems this is an active bug in the current release.

**Comment by EddyVerbruggen** [comment]
@Bramzor What do you mean by review? Happy to merge and publish anything, but can't really spend time on this atm.

**Pull request merged**
