### PR TITLE
Fixed a conflict with Push Notification Plugin

### PR DESCRIPTION
**Pull request by yehiasalam**
Hello, 

Please refer to https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/247#issuecomment-282163018

### CODE REVIEW

**Comment by js12690** [comment]
@yehiasalam @EddyVerbruggen Please fixed issue of conflict with push notification plugin as soon as possible

**Comment by enciphegraph** [comment]
@yehiasalam @EddyVerbruggen Any updates on when/if this will be done?

**Comment by renanccastro** [comment]
This is very important to be merged for us @EddyVerbruggen Can you help us here?

**Comment by EddyVerbruggen** [comment]
Just use the fork if you need this change.

If I understand correctly this PR will break the plugin in case you're *not* using the push notification plugin.

**Comment by fredgalvao** [comment]
@EddyVerbruggen the definitive solution to this is to use cocoapod-like framework reference instead of linking the libraries directly. `phonegap-plugin-push` has gone that route and upgraded to cocoapod references, and that allows it to coexist with any other plugin that might use a duplicate framework or library.

**Comment by EddyVerbruggen** [comment]
8.0.0 will use cocoapods. Thx!

**Pull request closed without merging**
