### PR TITLE
replace deprecated dependency plugin

### PR DESCRIPTION
**Pull request by minhtc**

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Thanks @minhtc! It would be great if people can confirm their Android builds work fine with this change. It's been added to the master branch.

**Comment by EddyVerbruggen** [comment]
@minhtc Did you succeed building with your changes?

**Comment by minhtc** [comment]
yes, I've tested on fresh phonegap project and It's working for me

**Comment by EddyVerbruggen** [comment]
Awesome - is there any hint you can give guys running into trouble after this change? See #65 #64..

**Pull request merged**
