### PR TITLE
chore: Support Cordova 9

### PR DESCRIPTION
**Pull request by gvhuyssteen**
As recommended by @meirg

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Looks legit, thanks!

**Comment by pghoratiu** [comment]
This change broke the build in my case with the following error:

> 
> Google Sign-In prerequisites
> Failed to install 'cordova-plugin-googleplus': Error: Cannot find module 'q'
>     at Function.Module._resolveFilename (module.js:548:1

Does this mean I need to include the Q library explicitly in the project?
Shouldn't the plugin list it as a dependency?

My environment:

```
   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.4
   @ionic/app-scripts : 3.2.3

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, (and 22 other plugins)

   Android SDK Tools : 26.1.1 (/Users/gabi/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v8.15.0 (/usr/local/Cellar/node@8/8.15.0/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2 Build version 10E125
```

**Comment by guylando** [comment]
In general probably better would be to add dynamic cordova version detection condition that require code.

@pghoratiu check in the hook if context.opts.cordova.version returns cordova version and if so then in the specified changes replace require by: (parseFloat(context.opts.cordova.version) >= 9 ? require : context.requireCordovaModule)

**Comment by guylando** [comment]
And if the change breaks compatibility with cordova 8 then probably better to update the readme

**Comment by hiepxanh** [comment]
hello, I seen this PR so long, can you merge this sir?

**Pull request merged**
