### PR TITLE
Android 6.0

### PR DESCRIPTION
**Pull request by randdusing**
Added call to request permission

May not be the cleanest implementation, nor was I able to test on Android versions prior to 6.0.

Based on Cordova's source code: https://github.com/apache/cordova-android/blob/000eb0916e505de0ef8f19397f54046844accdf0/framework/src/org/apache/cordova/CordovaInterfaceImpl.java hasPermission always returns true for Android versions prior to 6.0. So the added code shouldn't affect previous versions.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Very nice. The implementation looks good but it adds a dependency on the latest Cordova-Android release (the one that has the `hasPermission` and `requestPermission` methods.

That's not a problem for folks using API level 23 which requires this check anyway, but folks using cloud builds will run into trouble. So we need to make sure this also compiles correctly on API levels < 23.

**Comment by randdusing** [comment]
Is it even possible to compile correctly on API < 23 since it requires the newest Cordova Android release without using a different GooglePlus.java that doesn't include the cordova.hasPermission and cordova.requestPermission calls? Can you substitute an older version of GooglePlay.java if the targetSdk < 23?

I ran into similar issues with my Bluetooth LE plugin, but never found a good way to handle cloud users who couldn't set their target higher besides telling them to target an older version of the plugin.

**Comment by EddyVerbruggen** [comment]
There are a few options:
* Don't use `cordova.hasPermssion` convenience method but rather `ActivityCompat.requestPermissions` (which requires a dependency to a recent Android support library). That's what I've done for the BarcodeScanner plugin recently. Also in order to not break cloud builds.
* Use reflection. Not a best practice, but in this case IMO it's a defendable approach.

**Comment by randdusing** [comment]
Ahh, how long do you typically wait until "forcing" a higher target SDK requirement onto users? Or do you usually try to keep it as low as possible?

**Comment by EddyVerbruggen** [comment]
I typically keep the minimum version as low as possible. Especially for 'older' plugins so I don't force anyone to upgrade their platform. Folks may have very valid reasons not to upgrade to the latest Cordova every time.

If you're not a Java guy then I can take a stab at it. Just let me know. In any case I appreciate your work!

**Comment by randdusing** [comment]
Ahh ok, Java isn't my strongest suit. I'll just leave this here for people who are able to target a higher SDK or don't want to include Android support library.

**Comment by EddyVerbruggen** [comment]
I still like this, merged and will tweak a bit. Thx!

**Pull request merged**
