### PR TITLE
add support to ios9 with new google sign in framework

### PR DESCRIPTION
**Pull request by davyzhang**
ios9 with new framework

### CODE REVIEW

**Comment by zalatnaicsongor** [comment]
You seem to have forgotten the
    swizzleMethod([AppDelegate class],
                  @selector(application:openURL:options:),
                  @selector(identity_application:openURL:options:));
call from the load method. Without this call, it doesn't work for me.

**Comment by sammuggPS** [comment]
@davyzhang, something that doesn't sit right with me: In your version of GooglePlus.m you added a method that is virtually the same as the one before it.

Why did you implement it in that way? Why not just update the existing method?

**Comment by davyzhang** [comment]
sorry for quite a long time, I was busy with other stuff lately, I will take look at this pr as soon as possible

**Comment by chaffeqa** [comment]
looks like this is where cordova is going in general

[core committer](https://github.com/phonegap/phonegap-plugin-push/pull/1183)

is there anything i could help with for this?  does this pull request cover the new cordova api?

**Comment by EddyVerbruggen** [comment]
@chaffeqa What exactly do you refer to by 'this'? The link you provided is for finally adding Cocoapod support to Cordova, but that's not what this PR is about (looks like an update to the SignIn framework).

**Comment by chaffeqa** [comment]
derp yea sorry, didnt look deep enough into the actual pull.

I commented on this because i was looking for a solution to #247 which I also just ran into.

I will continue my discussion there

**Comment by EddyVerbruggen** [comment]
Integrated manually, thanks!

**Pull request closed without merging**
