### PR TITLE
Ios updated google framework

### PR DESCRIPTION
**Pull request by tomasbedrich**
Solves #112 and #90.

### CODE REVIEW

**Comment by visormatt** [comment]
@tomasbedrich have pulled down this branch but I still do not see any way to back out of the login flow. I was wondering if there were any additional steps required to enable this? Much appreciated!

**Comment by tomasbedrich** [comment]
@visormatt I had to do `cordova platform remove ios` and then `cordova platform add ios` again with my fork of this plugin. Hope it helps.

**Comment by visormatt** [comment]
@tomasbedrich 
That did the trick thank you! I though i had already tried that, but must have done so with the incorrect branch pulled down. Thanks for the quick response!

**Comment by tomasbedrich** [comment]
Glad to hear. :) But better to thank @phw for the fix!

**Comment by EddyVerbruggen** [comment]
Thank you guys, indeed the 2.4.0 iOS SDK uses SafariVC which has an option to cancel the OAuth flow. Awesome!

Available in version 4.0.6.

**Comment by phw** [comment]
Is there any minimum iOS version for this to work? I just tested this on iOS 7 and can't see the back button.

Also it looks like signin via the installed Google+ app stopped working, but that could be related to the recent large update of that app.

**Comment by tomasbedrich** [comment]
I have tested the plugin on iOS 9.1 iPhone model no. MD242D/A.

You are right regarding the Google+ app login. The plugin still opens the in-app browser, even if the app is installed.

**Comment by lukaszrozbicki** [comment]
Does anyone know how to fix opening in-app browser instead of installed Google app? It really bothers me and it isn't very comfortable for users.

**Comment by EddyVerbruggen** [comment]
Is your app allowed to launch the Google+ app?

**Comment by lukaszrozbicki** [comment]
Yes. I even reinstall Google app and my app to be sure. No effect.

**Pull request merged**
