### PR TITLE
Upgrade ios google auth sdk which now uses SFAuthenticationSession

### PR DESCRIPTION
**Pull request by guylando**
Upgrade to version 4.4.0 according to instructions here ("without cocoa pod"): https://developers.google.com/identity/sign-in/ios/sdk/

Note: The instructions have a bug because including GoogleSignInDependencies.framework library creates linkage errors as described here: https://stackoverflow.com/questions/41217839/duplicate-symbols-when-integrating-firebase-and-google-sign-in-sdks-manually-wit

Also the solution is described there which is to remove that framework.
Probably should test this on an app which doesn't use firebase just to make sure. I tested on an app WITH firebase.

This solves https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/445 and attempts to solve https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/585

However seems https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/585 isn't solved by this.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
I'd be happy to merge this PR, thanks!

Can anyone give it a shot and make sure it doesn't break anything?

**Comment by pschinis** [comment]
I'm currently using guylando's fork in my app because it fixes the SSO issue (except in cases where Safari cookies have been cleared). It seems to be working fine, but my app uses Firebase Analytics so it still needs to be tested on a non-Firebase app. 

One other thing, I was getting "undefined symbols for architecture" linker errors when building for iOS after I switched to his fork, which was fixed by installing the most recent GoogleSignIn pod, i.e. I adding this line to my app's podfile and running pod install:

`pod 'GoogleSignIn'`

It tried to install version 3.3.0 at first, which didn't work. But after running pod repo update it used 4.4.0 which matches the version the guylando branch and the linker errors were fixed. So once this gets merged would be good to add this to the documentation.

**Comment by guylando** [comment]
@pschinis 
1. For safari cookies thing: the new SSO model on ios is based on cookies so clearing them clears SSO memory and you can reproduce this with most apps on ios.
2. The architecture error: make sure you get the latest version of my fork where I added the missing GoogleSignIn bundle. It should work without your pod install command and I accidentally didn't push it to github and was working with it locally while my github fork version was missing it. I think if you try to remove and add my fork version it will work properly.
3. If you get wrong architecture errors when publishing ipa then follow this: http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

**Comment by pschinis** [comment]
@guylando 

I was using your most recent branch, but I think I figured out why I was getting those build errors despite having the updated GoogleSignIn.framework and GoogleSignIn.bundle in the plugin. Based on my Podfile.lock after adding GoogleSignIn, it looks like version 4.4.0 of the SDK has GTMSessionFetcher/Core as a dependency and that wasn't getting pulled in by my Firebase pods so the build was just breaking without it. 

Maybe I'm using a different version of Firebase than you and your version pulls in all the necessary dependencies. My app currently uses Firebase/Core 4.11.0 and FirebaseMessaging 2.0.8 and those pull in a bunch of other dependencies including GoogleToolboxForMac that GoogleSignIn needs, but apparently not GTMSessionFetcher.

But I realized you're not supposed to add stuff to the Podfile manually because it's auto-generated by cordova so I created my own fork (https://github.com/pschinis/cordova-plugin-googleplus) and deleted the GoogleSignIn.framework and GoogleSignIn.bundle files and replaced the framework/resource declaration in plugin.xml with the following:

`<framework src="GoogleSignIn" type="podspec" spec="~> 4.4.0"/>`

And now it's working perfectly. So I think that might be a good approach that would also address potential issues with non-Firebase apps, unless there's some reason to avoid depending on Cocoapods.

**Comment by guylando** [comment]
@pschinis I use this version:
<plugin name="cordova-plugin-firebase" spec="^2.0.5" />

**Comment by pschinis** [comment]
@guylando my app doesn't actually use the full Firebase plugin, just the Firebase analytics plugin and the phonegap push notification plugin which has Firebase Messaging as a dependency:

`<plugin name="cordova-plugin-firebase-analytics" spec="^0.13.0"/>
<plugin name="phonegap-plugin-push" spec="^2.1.3"/>
`

So it seems likely that's the cause of the difference.

**Comment by Unibozu** [comment]
We've tested @guylando fork on our application (Wriggle) and the new implementation seems to work as expected during testing - the new app version will go live in a few days. Now using his fork until this PR is merged.

**Comment by evertonrobertoauler** [comment]
Hi guys, while this is been updated and fixed, I'm using version ^5 on iOS, it still works perfectly fine, I will try to test this PR next week, but for now to release my app, version 5 works fine.

<plugin name="cordova-plugin-googleplus" spec="^5.3.2">

**Comment by EddyVerbruggen** [comment]
Closing in favor of a PR that uses cocoapods instead.

**Pull request closed without merging**
