### PR TITLE
add access_token retrieval

### PR DESCRIPTION
**Pull request by remster**
Hi Eddy,

As people frequently ask you for why you don't supply the access_token in your plugin, perhaps we could discuss this pull request.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hi,

I don't mind having that added at all.

I do like other folks to test your PR/fork before merging this though.

Btw, I'm not sure this plugin will play nicely with other plugins that also include a reference to okhttp (unless it's exactly the same version).

Thanks a lot!
Eddy

**Comment by remster** [comment]
Thanks Eddy.

Point taken on okhttp - this is a trivial http get exchange and as I am not a pro android/cordova developer - can you suggest a more bread and butter http library - something i can safely rely on in cordova? Tried [apache](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/DefaultHttpClient.html), but it wasn't there. Ideally something that doesn't make me introduce additional deps.

WRT testing - I had to verify this works for my needs of course - and since i had the code typed up i thought i ask you if you wanted it. I see no test code and testing authentication is difficult in an automated manner. I also can't see obvious contribution guidelines. How would you like me to test it?

Do you mind i provide a few edits (subject to your approval) to the README - things werent obvious and i had to scratch my head for quite a while. Might as well type up it in case other folks get confused.

**Comment by EddyVerbruggen** [comment]
Please go ahead with editing the readme. If it's unrelated to this PR please do it in a separate branch/PR so it can be merged as quickly as possible.

WRT testing I meant that I'd like others to try your code just to see if there's regression.

WRT the okhttp lib: I've used `HttpURLConnection` in the past on Android to avoid using an external lib. Seemed to do the job well for me (in this case I expect the remote to return a JSON object: {active: boolean}):

```java
  private void callUrl() {
    new HttpAsyncTask().execute("https://myurl");
  }

  private class HttpAsyncTask extends AsyncTask<String, Void, String> {
    @Override
    protected String doInBackground(String... urls) {
      return readJSONFeed(urls[0]);
    }

    @Override
    protected void onPostExecute(String result) {
      try {
        boolean valid = result != null && new JSONObject(result).getBoolean("active");
      } catch (JSONException ignore) {
      }
    }
  }

  private String readJSONFeed(String endpoint) {
    HttpURLConnection urlConnection = null;
    try {
      URL url = new URL(endpoint);
      urlConnection = (HttpURLConnection) url.openConnection();
      urlConnection.setInstanceFollowRedirects(true);
      InputStream in = new BufferedInputStream(urlConnection.getInputStream());
      return convertStreamToString(in);
    } catch (IOException e) {
      e.printStackTrace();
    } finally {
      if (urlConnection != null) {
        urlConnection.disconnect();
      }
    }
    return null;
  }
```

**Comment by remster** [comment]
Smashing! HttpURLConnection is there already. Bit low level, but deps management is a nightmare, so prolly a good idea. I should be able to find time to make amendments within the next 24hrs - it's best that you wait for them before you test your on your side.

**Comment by EddyVerbruggen** [comment]
Awesome! Take your time, I'm not going anywhere.

**Comment by remster** [comment]
Ok, Addressed best i could. see commit: https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/378/commits/7cd169a40d01069f978cbbb97a2582c89df41050

I have to say the README is generally hard to read. 
I documented accessToken supplied because this is what iOS does.
iOS doesn't offer expiry, which think is useful to the client, it does offer refereshToken, which i don't think is useful (tokens aren't refreshed by the client).

Anyho, please take a look at what i've cooked

**Comment by EddyVerbruggen** [comment]
Thanks @remster I like what you've cooked!

I'll grant you commit access to this repo, so if anything bothers you please feel free to change it.

Cheers,
Eddy

**Comment by theunreal** [comment]
How I can test it in my project? I tried to replace the `GooglePlus.java` with urs but it didn't do the trick

**Comment by zmilkman** [comment]
is this commit live in the NPM version yet?

**Comment by antoine92190** [comment]
@theunreal @zmilkman It is not live in the NPM version yet, but you can use the latest version with:
`cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus.git --variable REVERSED_CLIENT_ID=yourReverseId`

**Comment by EddyVerbruggen** [comment]
If the current code in the master branch is deemed stable then I'd gladly push an update to npm.

**Pull request merged**
